name: conditional-workflow
on: [push]
jobs:
  hello-world:
    #if: github.repository == 'octo-org/octo-repo-prod'
    if: github.repository == 'jarjr/Github-Examples'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World"
        run:  echo "Hello World!"
  goodbye-moon:
    runs-on: ubuntu-latest
    steps:
      - name: "Goodbye World"
        run:  echo "Goodbye Moon!"
      - name: "Hello New World"
        run:  echo "Hello New World!"