name: Build, Test, and Deploy Workflow

on:
  push:
    branches:
      - main

defaults: &defaults
  runs-on: ubuntu-latest

common_steps: &co_step
  - name: Checkout code
    uses: actions/checkout@v4

jobs:
  deploy:
    needs: [build, test]
    <<: *defaults
    steps:
      - <<: *co_step
      - name: Deploy application
        run: echo "Deploying to production..."
  build:
    runs-on: ubuntu-latest
    steps:
      - <<: *co_step
      - name: Build application
        run: echo "Building the application..."
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - <<: *co_step
      - name: Test application
        run: echo "Running tests..."
  log:
    if: always()
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - <<: *co_step
      - name: Logging message for CI/CD
        run: echo "Showing messages now..."        