name: Build, Test, and Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy application
        run: echo "Deploying to production..."
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build application
        run: echo "Building the application..."
      - name: Simulate failure
        run: exit 1  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test application
        run: echo "Running tests..."
  log:
    if: always()
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Logging message for CI/CD
        run: echo "Showing messages now..."        