name: Workflow commands

on:
  push:


jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: group log messages
        run: |
          echo "::group::My group Message"
          echo "Msg 1"
          echo "Mgs 2"
          echo "::endgroup::"
      - name: Step 1
        run: |
          echo "MY_VAL=hello" >> $GITHUB_ENV
      - name: Step 2
        run: |
          echo $GITHUB_ENV