name: Workflow commands

on:
  push:


jobs:
  my-job:
    runs-on: ubuntu
    steps:
      - name: group log messages
        run: |
          echo "::group::My group Message"
          echo "Msg 1"
          echo "Mgs 2"
          echo "::endgroup::"